### ISSUE TITLE
ee.Initialize() error

### ISSUE THREAD

**Issue by LightningRpper** [gee-community/qgis-earthengine-plugin#105]
Hello, I'm trying to run a Python file for Google Earth. That application unfortunately isn't taking python files so I'm trying to run it in VS code. When I put in this code here, 
`import ee
ee.Initialize()`
I get an error that says
`Exception has occurred: AttributeError
module 'collections' has no attribute 'Callable'`
Why is it saying that and what can I do to fix it?

**Comment by gena** [comment]
Google Earth or Google Earth Engine?

> That application unfortunately isn't taking python files
What application?

If your goal is just to run a Python script using EE API - you probably need to check https://developers.google.com/earth-engine/guides/python_install

**Comment by LightningRpper** [comment]
> 
> 
> Google Earth or Google Earth Engine?
> 
> > That application unfortunately isn't taking python files
> > What application?
> 
> If your goal is just to run a Python script using EE API - you probably need to check https://developers.google.com/earth-engine/guides/python_install

Google Earth. I input code that imported Earth Engine and initialized it to sync up with Google Earth but that has done nothing.

**Comment by gena** [comment]
> Google Earth. I input code that imported Earth Engine and initialized it to sync up with Google Earth but that has done nothing.

But this is the repository for QGIS Earth Engine plugin, please ask questions about Google Earth maybe in https://support.google.com/earth/?hl=en#topic=7364880

**Comment by mnowatzki** [comment]
> Hello, I'm trying to run a Python file for Google Earth. That application unfortunately isn't taking python files so I'm trying to run it in VS code. When I put in this code here, `import ee ee.Initialize()` I get an error that says `Exception has occurred: AttributeError module 'collections' has no attribute 'Callable'` Why is it saying that and what can I do to fix it?

Have you found a solution to this yet? Having the same issue...

**Comment by karina-marques** [comment]
I am having the same issue. Any help?

**Comment by XavierCLL** [comment]
Hi @mnowatzki @karina-marques @LightningRpper

The issue is not directly from this plugin, it comes from a library that uses _ee_ that is not yet compatible with Python 3.10, the (temporal) solution is using (downgrade) the Qgis with a Python < 3.10 (alternative use the Qgis from Conda)

Relate issue: https://github.com/google/earthengine-api/issues/181
