### ISSUE TITLE
Issue: install GEE plugin on QGIS

### ISSUE THREAD

**Issue by Fitzmon** [gee-community/qgis-earthengine-plugin#108]
Hey guys,

I met some issues when I installed the Google Earth Engine plugin on QGIS. I installed QGIS 3.22.5, miniconda and Jupiter notebook on my desktop. Now I am following the geemap tutorials on Youtube.

Issue 1
Under Python Console, the unauthorized error pops up when I execute import ee. This error disappears when I execute import ee again.

Issue 2
When I install GEE version 0.0.4, the authentication window does not pop up. I try to use ee.authenticate() to activate it but there is no place for me to input the token.

Thanks in advance!

**Comment by gena** [comment]
Could be due to the changes in EE authentication, can you authenticate outside of QGIS?

* pip install earthengine-api
* earthengine authenticate

Follow instructions, then restart QGIS and see if this helps.

**Comment by Fitzmon** [comment]
> Could be due to the changes in EE authentication, can you authenticate outside of QGIS?
> 
> * pip install earthengine-api
> * earthengine authenticate
> 
> Follow instructions, then restart QGIS and see if this helps.

I tired and poped up an error

> Fetching credentials using gcloud
> 'gcloud' is not recognized as an internal or external command,
> operable program or batch file.
> gcloud failed. Please check for any errors above and install gcloud if needed

And I use
> pip install gcloud

But the same error still pops up.

**Comment by gena** [comment]
Try installing gcloud using these instructions: https://cloud.google.com/sdk/docs/install#windows

**Comment by Fitzmon** [comment]
It works! Thank you so much!
