### ISSUE TITLE
TypeError: EarthEngineRasterDataProvider.readNativeAttributeTable() missing 1 required positional argument: 'errorMessage'

### ISSUE THREAD

**Issue by mvsc1** [gee-community/qgis-earthengine-plugin#146]
I am getting this error running a script in the earth engine python console:

TypeError: EarthEngineRasterDataProvider.readNativeAttributeTable() missing 1 required positional argument: 'errorMessage'

Currently no data is loading. Makes me think there is another error (in the script) which cannot be shown due to this issue.
Why is the argument not provided?

QGIS version: 3.36.2-Maidenhead Maidenhead, 6d250527 
Plugin version: 0.0.6
OS: Windows 11

**Comment by XavierCLL** [comment]
Hi @mvsc1 thanks, that was fixed in https://github.com/gee-community/qgis-earthengine-plugin/pull/140 but has not been released yet
