### ISSUE TITLE
Embed GEE Python library

### ISSUE THREAD

**Issue by XavierCLL** [gee-community/qgis-earthengine-plugin#15]

**Comment by gena** [comment]
This probably should use the following as a skeleton https://github.com/volaya/qgis-plugincreator-plugin/, and tested on Linux, Windows, MaxOS aftewards to make sure that everything runs fine.

**Comment by XavierCLL** [comment]
Implemented in 215ac7144583723a112b6f664ce5a6ea159edeff, this automatically install (if needed) and load all EE dependencies in the user space

**Comment by gena** [comment]
This does not seem to be robust enough, maybe it makes sense to implement installation and authentication in a branch to keep master stable, in order to test on all platforms and fix all bugs, this will may need some time for testing

![image](https://user-images.githubusercontent.com/169821/68628826-0880cc00-04e2-11ea-97ca-de5c0e1673fd.png)

**Comment by gena** [comment]
![image](https://user-images.githubusercontent.com/169821/68628945-61506480-04e2-11ea-8d04-4897f5094627.png)

**Comment by gena** [comment]
This does not seem to be stable, especially because it has to be tested on all platforms. Maybe it makes sense to implement installation + authentication in a branch first, make sure it works everywhere, to keep the master stable.

**Comment by gena** [comment]
... let me try to fix it on Windows ...

**Comment by XavierCLL** [comment]
It should be multiplatform, it could be specific of pyCrypto, I will check it too. And yes you are right about managing the development in branches (for the next features) but I think right now the plugin, in general, is in beta stage, that is a very good idea after first stable version, I did it in the main branch with the idea of push development.

**Comment by gena** [comment]
Migrated everything to use paver instead of on-the-fly installation (too shaky). The final plugin zip file is ~13Mb, supporting Windows, Linux, and MacOS.

**Comment by XavierCLL** [comment]
Hi Gena, we have lithe problem with this implementation, as it is currently is only compatible with 64bits system, or we generate the 32bits libraries too or we restricted to 64bits putting a note in the documentation.

**Comment by gena** [comment]
I'd limit it to 64bit for now, how many 32bit are out there? Otherwise, it's always possible to release a 32bit version and name it correspondingly in the plugins

**Comment by XavierCLL** [comment]
Yes I know, there are very few users of 32bits but it is good to clarify it

**Comment by XavierCLL** [comment]
I will test other possible issues with respect to compatibility across python versions, such as 3.6, 3.7 and 3.8. I don't sure but I will test it.

**Comment by gena** [comment]
I will mention this in the plugin description and/or release.

**Comment by XavierCLL** [comment]
I have tested using differents python versions (3.7 and 3.8 in Linux) and the plugin works fine, I discover that when I use different python respect to the embed library in the plugin it shows several errors about the file_cache, after research about it, that messages really are warnings and those messages do not affect the plugin, I fixed it in f3974375e2c71c9c9bfba6fde356014a07e0b704
