### ISSUE TITLE
Enable GitHub Pages

### ISSUE THREAD

**Issue by XavierCLL** [gee-community/qgis-earthengine-plugin#21]
Hi Gena, I don't have access in the settings, please could you enable the GitHub Pages in settings -> options and enable /docs folder similar to this:

![image](https://user-images.githubusercontent.com/11801453/68556907-f2431500-03e8-11ea-870c-b81e82800bc9.png)

**Comment by XavierCLL** [comment]
Hi Gena, If you want to give me the admin access to the repository to config and show you the idea of github pages to host the doc

**Comment by gena** [comment]
I've worked with GitHub pages a bit. Just published GitHub pages, it's a bit long URL https://gee-community.github.io/qgis-earthengine-plugin/, but should be fine for a redirect from the QGIS plugin docs. I've created the main repository as well for gee-community.github.io
