### ISSUE TITLE
Upload to repo as gee-community

### ISSUE THREAD

**Issue by XavierCLL** [gee-community/qgis-earthengine-plugin#27]
https://github.com/gee-community/qgis-earthengine-plugin/blob/cead21ccc10ba2aafe894f3cf5d1158dac2c1664/ee_plugin/metadata.txt#L14

What do you think if we create a generic user of gee-community? and upload it as gee-community

**Comment by gena** [comment]
I'd keep it like this, at least for now, it's good to have someone as a real contact person as well to keep this development progressing.

We should add contributors section, e.g. like https://github.com/vuejs/vue#contribution.

**Comment by XavierCLL** [comment]
Ok good!
