### ISSUE TITLE
Please confirm licence

### ISSUE THREAD

**Issue by pcav** [gee-community/qgis-earthengine-plugin#30]
Please confirm that the plugin do not infringe Google licences.
Thanks.

**Comment by gena** [comment]
The plugin itself is released as MIT and is based on the Google Earth Engine API: https://github.com/google/earthengine-api, which is also released under Apache 2.0, they are compatible, so no issues are expected. Just to be sure, @tylere may I ask to comment on this, does the source code look ok in terms of the license infringement?

**Comment by tylere** [comment]
The Apache 2.0 and MIT licenses are both permissive licenses, so I don't see any licensing issues related to installing and using them together.

**Comment by pcav** [comment]
Thanks
