### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by rauledop1** [gee-community/qgis-earthengine-plugin#34]
Hi,

I found this qgis plugin in the new plugin section and I think that is a powerfull tool.
I try to start this plugin with the "Hello word" examplo and I'cant run google earth engine app, always open authentification tab and show me a sign in code but don´t start this simple hello word example.

![image](https://user-images.githubusercontent.com/45100369/70080623-a77e7c80-15e5-11ea-8f70-3ebdaad73ba8.png)

help me please

**Comment by XavierCLL** [comment]
Hi @rauledop1, thanks for the report, could you paste the whole error? witch Windows version are you using? 64bits?

**Comment by rauledop1** [comment]
Yes I Used windows 64 bits, this is the complete report

![image](https://user-images.githubusercontent.com/45100369/70086736-b9661c80-15f1-11ea-97dd-8f3c7f081d0d.png)

I try run this app through work network, when I'm connect from my personal network this app run fine.

there is any way to run this app from my work network

**Comment by gena** [comment]
Can you access Earth Engine via your work network? Like https://code.earthengine.google.com/ and from Python? E.g. try running in a command prompt: ```earthengine task list```.

**Comment by PedroVenancio** [comment]
This seems a certificate error.

Can you try to install curl-ca-bundle package from OSGeo4W, as stated here

https://github.com/qgis/QGIS/issues/27159#issuecomment-555615692

and see if it solves the issue?

**Comment by zgcao** [comment]
It works very well in my Mac desktop. Form your command, it feels like a network problem. Did you use the VPN to access the google service?

**Comment by zgcao** [comment]
It works very well in my Mac desktop. Form your command, it feels like a network problem. Did you use the VPN to access the google service?

**Comment by rauledop1** [comment]
> Can you access Earth Engine via your work network? Like https://code.earthengine.google.com/ and from Python? E.g. try running in a command prompt: `earthengine task list`.

Yes, I can.

I work perfectly througth both ways,

**Comment by zgcao** [comment]
We have found a suggestion. You can manually authenticate GEE  to get credentials in the terminal: `earthengine authenticate`
