### ISSUE TITLE
Also implement ee_plugin.contrib.Map as a folium map

### ISSUE THREAD

**Issue by SiggyF** [gee-community/qgis-earthengine-plugin#38]
Then we can copy code between  qgis and notebooks for faster prototyping.

**Comment by fitoprincipe** [comment]
Hi developers,

I've code some stuff that can be useful in this and other milestones: https://github.com/fitoprincipe/ipygee. Unfortunately I don't have much time to contribute, but I'd really like to if I had some time. =)

**Comment by SiggyF** [comment]
Thanks I'll have a look.

**Comment by gena** [comment]
This should be supported alredy by the following project: https://github.com/giswqs/geemap
