### ISSUE TITLE
Map.addLayer using Python in QGIS

### ISSUE THREAD

**Issue by gena** [gee-community/qgis-earthengine-plugin#4]

**Comment by fitoprincipe** [comment]
Hi @gena, how is it going? although I have a lot going on in my actual job, I've been doing this (bringing EE into QGIS) myself, so I feel I could contribute, and I really would like to (although I don't really have much time). 

I am not sure if you have seen [ipygee](https://github.com/fitoprincipe/ipygee), but in that package I have worked on a `Map` class that inherits from `ipyleaflet.Map`. When I was thinking in creating this package myself I though I'd create a `Map` class that somehow inherits or wraps over the map canvas or the instance (`QgsProject.instance()`).. how did you think about it?

**Comment by fitoprincipe** [comment]
I guess this year you will work on this in the GEE User Summit Hackathon.. but I won't be there :disappointed: but I am happy to contribute from here :smile:

**Comment by fitoprincipe** [comment]
correction, I suppose you ARE in the hackathon right now =) I just realized... Great!

**Comment by gena** [comment]
Indeed, this issue was opened during a hackathon. I did not tag the sourcecode but the functionality required for Map.addLauer is implemented already.
