### ISSUE TITLE
GSOC 2020 QGIS earthengine plugin

### ISSUE THREAD

**Issue by hello-deepak** [gee-community/qgis-earthengine-plugin#40]
Hello Everyone,

I dont have any issues. I just want to contribute to this QGIS earth engine plugin. Is there any way I can contribute through Google Summer of Code(GSOC)?

**Comment by gena** [comment]
Have to check with GSOC organizers, maybe developing a CI for at least three platforms, or picking up some of the issues (this requires coding skills)

**Comment by gena** [comment]
Unfortunately, we don't do any developments via GSOC, maybe in the future.
