### ISSUE TITLE
Displaying FeatureCollection

### ISSUE THREAD

**Issue by giswqs** [gee-community/qgis-earthengine-plugin#41]
It seems the `Map.addLayer()` function renders FeatureCollection differently than the GEE Code Editor. By default, the FeatureCollection is display as all black, which makes it difficult to distinguish individual features within a FeatureCollection. See below.  

```
import ee
from ee_plugin import Map

fc = ee.FeatureCollection('TIGER/2018/States')

image = ee.Image().paint(fc, 0, 2)
Map.setCenter(-99.844, 37.649, 5)
Map.addLayer(image, {'palette': 'FF0000'}, 'TIGER/2018/States')
Map.addLayer(fc, {}, 'US States')  # This layer is all black
```

![](https://i.imgur.com/kH7qCSU.png)

[GEE script](https://code.earthengine.google.com/?scriptPath=Examples:Datasets/TIGER_2018_States)
![](https://i.imgur.com/CDH3jEI.png)

**Comment by gena** [comment]
Thanks for reporting, this will be fixed in the next release.

![image](https://user-images.githubusercontent.com/169821/71419699-13965280-2671-11ea-8e48-df0ff2cfc921.png)

**Comment by giswqs** [comment]
@gena Awesome! Thanks for the quick fix.
