### ISSUE TITLE
Map.centerObject() function not accepting Geometry

### ISSUE THREAD

**Issue by giswqs** [gee-community/qgis-earthengine-plugin#42]
It seems the `Map.centerObject()` function only accepts a FeatureCollection as a parameter. It would be nice if it can also accept a Geometry as a parameter. In this way, it behaves the same way as the [JavaScript version](https://developers.google.com/earth-engine/geometry_visualization_info#visualizing-geometries). 

```
import ee 
from ee_plugin import Map 

# Create a geodesic polygon.
polygon = ee.Geometry.Polygon([
  [[-5, 40], [65, 40], [65, 60], [-5, 60], [-5, 60]]
])

# Create a planar polygon.
planarPolygon = ee.Geometry(polygon, {}, False)

# polygon = ee.FeatureCollection(polygon)
# planarPolygon = ee.FeatureCollection(planarPolygon)

# Display the polygons by adding them to the map.
Map.centerObject(polygon)
Map.addLayer(polygon, {'color': 'FF0000'}, 'geodesic polygon')
Map.addLayer(planarPolygon, {'color': '000000'}, 'planar polygon')
```

**Comment by gena** [comment]
Thanks for testing!

**Comment by gena** [comment]
The code is being reorganized a bit for the feature info tool. This will be fixed once everything is merged back into master.

**Comment by gena** [comment]
Should work  in the new release
