### ISSUE TITLE
Map.addLayer() resulting in KeyError: 'ee_plugin'

### ISSUE THREAD

**Issue by spacefan** [gee-community/qgis-earthengine-plugin#49]
**1. Problem description**
When i run the fellow code, everything is OK:

```python
# -*- coding:utf-8 -*-
import ee
from ee_plugin import Map

image = ee.Image('USGS/SRTMGL1_003').unitScale(0, 5000)
```

but KeyError: 'ee_plugin' error occured after execlute Map.addLayer():

```python
Map.addLayer(image, {'palette': ['blue', 'red'], 'min': 0, 'max': 1000}, 'dem', True)
```

![KeyError: 'ee_plugin' error](https://img-blog.csdnimg.cn/20200118231306292.PNG?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NwYWNlZmFu,size_16,color_FFFFFF,t_70)

**2. Enviorment**

OS: Win 10 x64
QGIS: 3.10.1
Python: 3.7.0

**Comment by gena** [comment]
This looks like something is wrong with the QGIS plugins dictionary. Can you check if the plugin is enabled in the Plugins > Manage and Install Plugins ...? Does this occur every time?

**Comment by spacefan** [comment]
When i restart QGIS, QGIS throw an exception:

```
Couldn't load plugin 'ee_plugin' due to an error when calling its classFactory() method 
```

but **Google Earth Engine** is enabled, and the fellow code can be execluted without error in Python console:

```python
# -*- coding:utf-8 -*-
import ee
from ee_plugin import Map

image = ee.Image('USGS/SRTMGL1_003').unitScale(0, 5000)
```

**Comment by spacefan** [comment]
Problem solved, thanks for your kind replay! @gena

**Comment by xtnncherish315** [comment]
> Problem solved, thanks for your kind replay! @gena

had the same problem.how you fix it?

**Comment by ChongyouXu** [comment]
> Problem solved, thanks for your kind replay! @gena

How to solve this problem, looking forward to your reply！

**Comment by ChongyouXu** [comment]
> This looks like something is wrong with the QGIS plugins dictionary. Can you check if the plugin is enabled in the Plugins > Manage and Install Plugins ...? Does this occur every time?

Hello, we encountered the same problem, but no solution has been found so far. 
Can you help us solve this problem？
![image](https://user-images.githubusercontent.com/32831575/83944856-3b512f80-a839-11ea-9d3f-44600d8640e0.png)
