### ISSUE TITLE
Upgrade EE library to 0.1.224 and release minor 0.0.2 version

### ISSUE THREAD

**Issue by gena** [gee-community/qgis-earthengine-plugin#54]
Make it work for all supported platforms:
* [x] Windows
* [x] Linux
* [x] macOS

**Comment by jdbcode** [comment]
Thanks for doing this! Let me know if I can help spread the word about folks needing to update to 0.0.2 when it is released.

**Comment by gena** [comment]
I've decided to move new small features into a separate release and focus only on the EE lib update for 0.0.2, new features still need some testing

**Comment by gena** [comment]
Updated to 0.0.2
