### ISSUE TITLE
Scrap EE Data Catalog items

### ISSUE THREAD

**Issue by gena** [gee-community/qgis-earthengine-plugin#6]
1. WMTS proxy (you need to run it as your own appengine app):
https://github.com/google/earthengine-api/tree/master/demos/wmts 
(it's a part of our open source Python client) 

2. Catalog is exported in the STAC format to gs://earthengine-stac/catalog
Browsable as https://console.cloud.google.com/storage/browser/earthengine-stac/catalog

**Comment by gena** [comment]
```
image = ee.ImageCollection('COPERNICUS/S2').filterDate('2018-01-01', '2018-01-02').median().divide(10000).visualize(**{'bands': ['B12', 'B8', 'B4'], 'min':0.05, 'max': 0.5})
image.getMapId()
{'mapid': '67e1bc56c3324c33d0729f2b281a9c37', 'token': 'a6a68799a198b1599a6eadf4910013d7', 'tile_fetcher': <ee.data.TileFetcher object at 0x0000027C416AA940>, 'image': <ee.image.Image object at 0x0000027C4145B3C8>}
```

**Comment by XavierCLL** [comment]
not necessary at this time see #18
