### ISSUE TITLE
Release v0.0.3

### ISSUE THREAD

**Issue by XavierCLL** [gee-community/qgis-earthengine-plugin#71]
There have been important bugfixes since v0.0.2 affecting new users

v0.0.3

-  EE raster layer inspector
-  Show some useful EE properties (bands, value types) in QGIS layer properties dialog
-  Fix GEE url authentication function if the credentials is not exists #63
-  Fix crash if the authentication dialog is cancelled or not filled by the user
-  Init the Google Earth Engine user authorization system only when the user is going to use the plugin
-  Fixed the authentication dialog when the url shortener doesn't work by any reason #66
-  Fix loading extra python dependencies to the plugin, fix #62

**Comment by XavierCLL** [comment]
@gena why you versioning in Qgis plugin as 0.0.3? it should be 0.3

**Comment by gena** [comment]
I'm trying to release it, the only concerns I have right now is that:

* we did not test it on all platforms yet 
* there are some breaking changes with regards to QGIS file formats - users will have to re-run their scripts to make QGIS projects working

**Comment by gena** [comment]
> @gena why you versioning in Qgis plugin as 0.0.3? it should be 0.3 ([6ca259e](https://github.com/gee-community/qgis-earthengine-plugin/commit/6ca259e25adf3a791f0413373aa6110c3bac3852))

It was actually 0.0.1, 0.0.2 in the previous releases (see tags, etc.), maybe we should update readme to keep it in-sync

**Comment by XavierCLL** [comment]
> I'm trying to release it, the only concerns I have right now is that:
> 
> * we did not test it on all platforms yet

I tested all the changes made in Linux and Windows, and some of then in Mac

> * there are some breaking changes with regards to QGIS file formats - users will have to re-run their scripts to make QGIS projects working

what changes are you talking about?

**Comment by XavierCLL** [comment]
> > @gena why you versioning in Qgis plugin as 0.0.3? it should be 0.3 ([6ca259e](https://github.com/gee-community/qgis-earthengine-plugin/commit/6ca259e25adf3a791f0413373aa6110c3bac3852))
> 
> It was actually 0.0.1, 0.0.2 in the previous releases (see tags, etc.), maybe we should update readme to keep it in-sync

to be honest, I prefer 0.3 because 0.0.3 seems a plugin very unfunctional and incomplete, but the plugin is completely functional maybe not complete until release 1.0

**Comment by gena** [comment]
It is a very bad error-prone practice to change the version of released software (tags, zip files, etc.) - let's stay backwards-compatible for now to avoid generating new errors and then update it in the next release, maybe v1.0.0 somewhere Q1 21 after adding a few major features. The last number current is updated indicating a bugfix path, e.g. https://en.wikipedia.org/wiki/Software_versioning

**Comment by gena** [comment]
> > * there are some breaking changes with regards to QGIS file formats - users will have to re-run their scripts to make QGIS projects working
> 
> what changes are you talking about?

https://github.com/gee-community/qgis-earthengine-plugin/commit/36f449f02cb3c5542dceb0c9ca43cab2a9b0caac

**Comment by gena** [comment]
So, to actually release the v0.0.3, we need to make sure that we have tested and fixed bugs related to the following scenario:

Save the QGIS project containing EE layers (vector and raster) in v0.0.2 format and then try to re-open using v0.0.3 version, making sure nothing is broken and layers (properties) are updated smoothly (testing save / load using new version as well). Once this goes smoothly and everything is tested (e.g. experimental v0.0.3 version is also confirmed to work by @rahulkgour in issue #70 ) - I will release it as stable.

**Comment by XavierCLL** [comment]
Sound good, I'll find some time in the following days to testing changes in v0.0.3, mainly the EE raster layer inspector changes (the #70 is the same that issue  #62 that is why I closed it, but I ok to wait for the feedback)

**Comment by gena** [comment]
I've tried releasing 0.0.3, but somehow it's not automatically approved in QGIS, strange, hopefully, will be picked up by someone from QGIS so we can close this
 
![image](https://user-images.githubusercontent.com/169821/103623030-cc0afd80-4f37-11eb-9ce3-bdf144a8aa3b.png)

**Comment by gena** [comment]
Released
