### ISSUE TITLE
Trouble Authenticating in Qgis version 3.16-3

### ISSUE THREAD

**Issue by Ash888-lab** [gee-community/qgis-earthengine-plugin#86]
Hii there. I am pretty much new to Github. Do pardon any convention errors I might be committing. I recently installed Google Earth Engine Plugin in Qgis Version 3.16-3. The authenticate option didn't come up after the install and I tried to authenticate using the python console. It did successfully open a browser window having the authentication key but when I came back to try to paste the key there was no option to do so. The running instance had already been terminated with errors. Am attaching the screenshot of the same. Any help is much appreciated.
Regards
Ash
![image](https://user-images.githubusercontent.com/54743457/106359637-f9ca4300-6339-11eb-9e1e-a6cff758b1fb.png)

**Comment by XavierCLL** [comment]
Hi, 
The plugin's authentication dialog comes up when you use it, run in the Python console in Qgis:
`from ee_plugin import Map`
Or run an example

**Comment by gena** [comment]
@Ash888-lab, if you'd like to authenticate manually - you need to run `earthengine authenticate` in an ordinary python console (not in the QGIS python console)

**Comment by Ash888-lab** [comment]
@XavierCLL @gena  Much thanks. Now when I tried its working fine. Once again thanks so much for the quick reply.
